### ISSUE TITLE
Unnecessary selections

### ISSUE THREAD

**Issue by ozguncagri** [yishn/tikzcd-editor#14]
Sometimes drag operations makes you select unnecessary things on editor. It can be prevent with `user-select: none` kind of style for better user experience. A picture is worth a thousand words;

<img width="415" alt="screen shot 2017-11-04 at 03 15 12" src="https://user-images.githubusercontent.com/946294/32400283-1c9062dc-c10f-11e7-9f84-6d95d2781874.png">

Thanks for editor BTW :)

**Comment by yishn** [comment]
Thank you! That's odd, I already have a user-select rule:

https://github.com/yishn/tikzcd-editor/blob/abab9db98439736d4294606d905c20f96fe345ff/css/master.css#L5-L6

Which browser are you using? Maybe we need to add more vendor-specific CSS...

**Comment by ozguncagri** [comment]
Maybe you should add another rule with `-webkit` prefix. Because I was trying it on Safari 11.0.1. I found this cross-browser solution on stack-overflow;

```css
.noselect {
  -webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Safari */
     -khtml-user-select: none; /* Konqueror HTML */
       -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* Internet Explorer/Edge */
            user-select: none; /* Non-prefixed version, currently supported by Chrome and Opera */
}
```
